export const SHIPPING = {
  PERSONAL: 'PERSONAL',
  PACKAGE_STANDARD: 'PACKAGE_STANDARD',
  PACKAGE_OVERLOAD: 'PACKAGE_OVERLOAD',
  LOCAL_DELIVERY: 'LOCAL_DELIVERY',
  COUNTRY_DELIVERY: 'COUNTRY_DELIVERY',
};

export const PRODUCTS = {
  SINGLE_DIBOND: 'SINGLE_DIBOND',
  SINGLE_ALU_PLEX: 'SINGLE_ALU_PLEX',
  SINGLE_ALU_STRETCH: 'SINGLE_ALU_STRETCH',
  SINGLE_ALU_SHAPE: 'SINGLE_ALU_SHAPE',
  DOUBLE_DIBOND: 'DOUBLE_DIBOND',
  DOUBLE_ALU_PLEX: 'DOUBLE_ALU_PLEX',
  DOUBLE_ALU_SHAPE: 'DOUBLE_ALU_SHAPE',
};

export const COLORS = {
  BLACK_MAT: 'BLACK_MAT',
  BLACK_GLOSSY: 'BLACK_GLOSSY',
  WHITE_MAT: 'WHITE_MAT',
  WHITE_GLOSSY: 'WHITE_GLOSSY',
  BRUSHED_ALUMINIUM: 'BRUSHED_ALUMINIUM',
  ANTHRACITE: 'ANTHRACITE',
  FOIL_CMYK_MAT: 'FOIL_CMYK_MAT',
  FOIL_CMYK_GLOSSY: 'FOIL_CMYK_GLOSSY',
  FOIL_PALETTE_GLOSSY: 'FOIL_PALETTE_GLOSSY',
  RAW_ALUMINIUM: 'RAW_ALUMINIUM',
  CUSTOM_RAL: 'CUSTOM_RAL',
  TAPE_RAL: 'TAPE_RAL',
  TAPE_SPECIAL: 'TAPE_SPECIAL',
};

export const LIGHTING = {
  WHITE: 'WHITE',
  PALETTE: 'PALETTE',
  CUSTOM_UV: 'CUSTOM_UV',
};

export const COLOR_SETS = {
  ORACAL_8500: 'ORACAL_8500',
  ORACAL_551: 'ORACAL_551',
  TAPES_RAL: 'TAPES_RAL',
  TAPES_SPECIAL: 'TAPES_SPECIAL',
};

export const SHAPES = {
  CROSS: 'CROSS',
  ELIPSYS: 'ELIPSYS',
  CIRCLE: 'CIRCLE',
  ROUNDED: 'ROUNDED',
};

export const TAPE_TYPES = {
  FLAT: 'FLAT',
  DOUBLE_FOLDED: 'DOUBLE_FOLDED',
};

export const REVISION_SIDES = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  UP: 'UP',
  DOWN: 'DOWN',
};
